# Generated by Django 4.0.4 on 2022-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('relationship', models.TextField()),
                ('phone_number', models.CharField(max_length=9)),
                ('birth_date', models.CharField(max_length=8)),
            ],
        ),
    ]
