# Generated by Django 4.0.4 on 2022-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='persona',
            name='birth_date_d',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='birth_date_m',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='birth_date_y',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
