# Generated by Django 4.0.4 on 2022-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_remove_persona_birth_date_persona_birth_date_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='phone_number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
