# Generated by Django 4.0.4 on 2022-05-24 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_persona_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='birth_date_d',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='birth_date_m',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='birth_date_y',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
