# Generated by Django 4.0.4 on 2022-05-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_alter_persona_birth_date_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='birth_date_d',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='birth_date_m',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='birth_date_y',
        ),
    ]
