# Generated by Django 4.0.4 on 2022-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0005_remove_persona_birth_date_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
