# Generated by Django 4.0.4 on 2022-05-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0007_alter_persona_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
