# Generated by Django 4.0.4 on 2022-06-02 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0008_alter_persona_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Telephone number must contain 9 digits'), django.core.validators.MaxValueValidator(999999999, message='Telephone number must contain 9 digits')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='relationship',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
