# Generated by Django 4.0.4 on 2022-06-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0009_alter_persona_name_alter_persona_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('NA', 'Does not apply'), ('ST', 'Student'), ('UE', 'Unemployed'), ('EM', 'Employed')], default='EM', max_length=20)),
            ],
        ),
    ]
