# Generated by Django 4.0.4 on 2022-06-05 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0011_persona_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='document_id',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000, message='Document ID must contain 8 digits'), django.core.validators.MaxValueValidator(99999999, message='Document ID must contain 8 digits')]),
        ),
    ]
