# Generated by Django 4.0.4 on 2022-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0012_alter_persona_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ssc',
            field=models.BooleanField(null=True),
        ),
    ]
