# Generated by Django 4.0.4 on 2022-06-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0013_job_ssc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ssc',
            field=models.BooleanField(null=True, verbose_name='Social Security Number'),
        ),
    ]
