# Generated by Django 4.0.4 on 2022-06-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0014_alter_job_ssc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ssc',
        ),
    ]
