# Generated by Django 4.0.4 on 2022-06-05 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0015_remove_job_ssc'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='health_insurance',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Telephone number must contain 9 digits'), django.core.validators.MaxValueValidator(999999999, message='Telephone number must contain 9 digits')], verbose_name='Health Insurance ID'),
        ),
    ]
