# Generated by Django 4.0.4 on 2022-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0016_job_health_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='relationship',
        ),
        migrations.AddField(
            model_name='persona',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='Single', max_length=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='rol',
            field=models.CharField(choices=[('Not Apt', 'Not apt'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Retired', 'Retired')], default='EM', max_length=20),
        ),
    ]
