# Generated by Django 4.0.4 on 2022-06-06 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0017_remove_persona_relationship_persona_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='health_insurance',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000, message='Telephone number must contain 9 digits'), django.core.validators.MaxValueValidator(999999999, message='Telephone number must contain 9 digits')], verbose_name='Health Insurance ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='document_id',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000, message='Document ID must contain 8 digits'), django.core.validators.MaxValueValidator(99999999, message='Document ID must contain 8 digits')]),
        ),
    ]
