# Generated by Django 4.0.4 on 2022-06-06 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0020_migration_alter_persona_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='passport_id',
            field=models.PositiveIntegerField(error_messages={'unique': 'A user with this passport_id ID already exists'}, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000, message='Passport ID must contain 8 digits'), django.core.validators.MaxValueValidator(99999999, message='Passport ID must contain 8 digits')], verbose_name='Passport ID'),
        ),
    ]
