# Generated by Django 4.0.4 on 2022-06-06 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0021_alter_migration_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='passport_id',
            field=models.PositiveIntegerField(error_messages={'unique': 'A user with this passport_id ID already exists'}, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000, message='Passport ID must contain 9 digits'), django.core.validators.MaxValueValidator(999999999, message='Passport ID must contain 9 digits')], verbose_name='Passport ID'),
        ),
    ]
