# Generated by Django 4.0.4 on 2022-06-06 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0025_alter_persona_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='document_id',
            field=models.PositiveIntegerField(error_messages={'unique': 'A user with this document ID already exists'}, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000, message='Document ID must contain 8 numbers'), django.core.validators.MaxValueValidator(99999999, message='Document ID must contain 8 numbers')], verbose_name='Document ID'),
        ),
    ]
