# Generated by Django 4.0.4 on 2022-06-06 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0026_alter_persona_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='health_insurance',
            field=models.PositiveIntegerField(error_messages={'unique': 'A user with this Health Insurance ID already exists'}, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000, message='Health Insurance ID must contain 8 numbers'), django.core.validators.MaxValueValidator(999999999, message='Health Insurance ID must contain 8 numbers')], verbose_name='Health Insurance ID'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='passport_id',
            field=models.PositiveIntegerField(error_messages={'unique': 'A user with this passport ID already exists'}, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000, message='Passport ID must contain 8 numbers'), django.core.validators.MaxValueValidator(999999999, message='Passport ID must contain 8 numbers')], verbose_name='Passport ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Phone number must contain 8 numbers'), django.core.validators.MaxValueValidator(999999999, message='Phone number must contain 8 numbers')]),
        ),
    ]
